name: Get daily score
on:
  schedule:
    # Run at 7:00am every day
    - cron: "0 7 * * *"
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: false
    - name: Set up Python
      uses: actions/setup-python@v4
    - name: Run todays check
      run: python today.py
    # TODO commit updated history to repo
    # TODO how can we report the new results?
