name: Get daily score
on:
  schedule:
    # Run at 7:00am every day
    - cron: "0 7 * * *"
  workflow_dispatch:
permissions:
  contents: write
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: false
    - name: Set up Python
      uses: actions/setup-python@v4
    - name: Run todays check
      run: python today.py
    - name: Commit updated historical results
      run: |
        git config --global user.name 'Austin Owensby'
        git config --global user.email 'austin-owensby@users.noreply.github.com'
        git commit -am "Automated daily update"
        git push
