name: Get daily score
on:
  schedule:
    # Run at 7:00am every day
    - cron: "0 7 * * *"
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    environment: pytest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: false
    - name: Run todays check
      run: python today.py
