name: Get daily score
on:
  schedule:
    # Run at 7:00am CST every day
    - cron: "0 12 * * *"
  workflow_dispatch:
permissions:
  contents: write
jobs:
  run:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: false
    - name: Set up Python
      uses: actions/setup-python@v4
    - name: Run todays check
      id: runPython
      run: |
        result="$(python today.py)"
        echo "result=$result" >> "$GITHUB_OUTPUT"
    - name: Send message to Slack
      run: |
        curl -X POST "${{ secrets.SLACK_ROUTE }}" \
             -H "Content-Type: application/json" \
             -d '{"text": "'"${{ steps.runPython.outputs.result }}"'"}'
    - name: Report error
      run: |
        if [[ -f "error.txt" ]]; then
          cat error.txt
          exit 1
        fi
    - name: Commit updated historical results
      run: |
        git config --global user.name 'Austin Owensby'
        git config --global user.email 'austin-owensby@users.noreply.github.com'
        git commit -am "Automated daily update"
        git push
